[supabase]
SUPABASE_URL="https://zgzqvgbergqnckguoyer.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnenF2Z2JlcmdxbmNrZ3VveWVyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTg1Nzc3OSwiZXhwIjoyMDgxNDMzNzc5fQ.AOsaHPu5FPLllXRzsOBwYwZD-FYij4CzJY2D_u_X4Qo"