[supabase]
SUPABASE_URL="https://zgzqvgbergqnckguoyer.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnenF2Z2JlcmdxbmNrZ3VveWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4NTc3NzksImV4cCI6MjA4MTQzMzc3OX0.AEfAgJl8ykS7Akf30AMU0CyvwxWLdfcnaWD7jAS0Hfo"
